const LABELS: Record<string, string> = {
  "auth.login": "Signed in",
  "auth.login_failed": "Failed sign-in attempt",
  "auth.logout": "Signed out",
  "auth.register": "Account created",
  "auth.email_verified": "Email verified",
  "auth.password_reset_requested": "Password reset requested",
  "auth.password_reset": "Password reset",
  "auth.password_changed": "Password changed",
  "auth.sessions_revoked": "Signed out on all devices",
  "settings.profile_updated": "Profile updated",
  "settings.changed": "Settings changed",
  "account.created": "Account added",
  "account.updated": "Account updated",
  "account.deleted": "Account removed",
  "credit_card.created": "Credit card added",
  "credit_card.updated": "Credit card updated",
  "credit_card.deleted": "Credit card removed",
  "transaction.created": "Transaction added",
  "transaction.updated": "Transaction edited",
  "transaction.deleted": "Transaction deleted",
  "category.created": "Category added",
  "category.updated": "Category updated",
  "category.deleted": "Category removed",
  "rule.created": "Rule added",
  "rule.updated": "Rule updated",
  "rule.deleted": "Rule deleted",
  "rule.applied_to_existing": "Rules applied to uncategorized transactions",
  "loan.created": "Loan added",
  "loan.updated": "Loan updated",
  "loan.deleted": "Loan removed",
  "loan.payment_recorded": "Loan payment recorded",
  "loan.payment_deleted": "Loan payment deleted",
  "loan.rate_revised": "Loan interest rate revised",
  "import.uploaded": "Statement uploaded",
  "import.completed": "Statement imported",
  "import.undone": "Import undone",
  "duplicate.resolved": "Duplicate reviewed",
  "review.resolved": "Imported transaction reviewed",
};

export function describeAuditAction(action: string): string {
  return LABELS[action] ?? action.replace(/[._]/g, " ");
}
